In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score

dataset = pd.read_csv("iris.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

classifier = KNeighborsClassifier(n_neighbors=50)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)
print("Accuracy :",accuracy)

for(i,j) in zip(y_pred,y_test):
    if i != j:
        print("actual value:",i,"\npredicted value :",j)
print("Number of mislabeled points from test data set :",(y_test != y_pred).sum())

Accuracy : 0.9333333333333333
actual value: Virginica 
predicted value : Versicolor
actual value: Versicolor 
predicted value : Virginica
Number of mislabeled points from test data set : 2


In [3]:
from sklearn.metrics import classification_report, confusion_matrix
print("-----Confusion Matrix-----")
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print("-----Classification Report-----")
print(classification_report(y_test,y_pred))

-----Confusion Matrix-----

[[11  0  0]
 [ 0 11  1]
 [ 0  1  6]]

-----Classification Report-----
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        11
  Versicolor       0.92      0.92      0.92        12
   Virginica       0.86      0.86      0.86         7

    accuracy                           0.93        30
   macro avg       0.92      0.92      0.92        30
weighted avg       0.93      0.93      0.93        30



In [4]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0       Setosa           Setosa
1   Versicolor       Versicolor
2       Setosa           Setosa
3   Versicolor       Versicolor
4   Versicolor        Virginica
5   Versicolor       Versicolor
6    Virginica        Virginica
7    Virginica        Virginica
8    Virginica       Versicolor
9    Virginica        Virginica
10   Virginica        Virginica
11      Setosa           Setosa
12  Versicolor       Versicolor
13  Versicolor       Versicolor
14  Versicolor       Versicolor
15  Versicolor       Versicolor
16      Setosa           Setosa
17  Versicolor       Versicolor
18   Virginica        Virginica
19  Versicolor       Versicolor
20   Virginica        Virginica
21      Setosa           Setosa
22      Setosa           Setosa
23      Setosa           Setosa
24  Versicolor       Versicolor
25  Versicolor       Versicolor
26      Setosa           Setosa
27      Setosa           Setosa
28      Setosa           Setosa
29      Setosa           Setosa